language:
  - ruby
rvm:
  - 2.3.0
jdk:
  - oraclejdk7

notifications:
  email: false

services:
  - mysql

install: true

before_script:
  - export RAILS_ENV=development
  - unset BUNDLE_GEMFILE

script:
  - mvn test -B -Pmysql
