language:
  - java

jdk:
  - oraclejdk7

notifications:
  email: false

services:
  - mysql

install:
  - rvm install 1.8.7

before_script:
  - export RAILS_ENV=development
  - test/select-dbms.sh mysql
