language:
  - ruby

rvm:
  - 2.3.0

jdk:
  - oraclejdk8

notifications:
  email: false

services:
  - mysql

install: true

before_script:
  - export RAILS_ENV=development
  # This variable needs to be unset because after rvm installs ruby 2.3, BUNDLE_GEMFILE is set to the
  # Gemfile under the root path, which fails the dependency installation in the two test projects.
  - unset BUNDLE_GEMFILE

script:
  - mvn test -B -Pmysql
